-- Concede todas as permissões necessárias
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO estudante;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO estudante;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO estudante;

-- Permissões para objetos futuros
ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT ALL PRIVILEGES ON TABLES TO estudante;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT ALL PRIVILEGES ON SEQUENCES TO estudante;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT ALL PRIVILEGES ON FUNCTIONS TO estudante;