-- --------------------------------------------------------------------------------------
-- Data Criacao ...........: xx/xx/xxxx                                                --
-- Autor(es) ..............:                                                           --
-- Versao ..............: 1.0                                                          --
-- Banco de Dados .........: PostgreSQL                                                --
-- Descricao .........: Carga de todas as tabelas do banco de dados.                   --
-- --------------------------------------------------------------------------------------
-- | Atualizacao : xx/xx/xxxx | Autor(es):                                      |      --
--                            | Descricao: Inclusão das linhas de INSERT INTO   |      --
-- | Atualizacao : xx/xx/xxxx | Autor(es):                                      |      --
--                            | Descricao: Correção das linhas de INSERT INTO   |      --
-- --------------------------------------------------------------------------------------
