-- --------------------------------------------------------------------------------------
-- Data Criacao ...........: xx/xx/xxxx                                                --
-- Autor(es) ..............:                                                           --
-- Versao ..............: 1.0                                                          --
-- Banco de Dados .........: PostgreSQL                                                --
-- Descricao .........: Consulta das tabelas do banco de dados.                        --
-- --------------------------------------------------------------------------------------
-- | Atualizacao : xx/xx/xxxx | Autor(es):         |  --
--                            | Descricao: Inclusão das consultas do banco de dados |  --
-- --------------------------------------------------------------------------------------
